import 'package:test_test_test/config/app_string/app_key_string_ternationalization.dart';

class AppFa {
   static Map<String, dynamic> fa = {
     AppKeyLocalization.label1: 'Item',
     AppKeyLocalization.label2: 'Newest',
     AppKeyLocalization.label3: 'Map',
     AppKeyLocalization.label4: 'Oldest',
     AppKeyLocalization.label5: 'Popular',
     AppKeyLocalization.label6: 'Add',
     AppKeyLocalization.label7: 'Home Location',
     AppKeyLocalization.label8: 'Education',
     AppKeyLocalization.label9: 'Job',
     AppKeyLocalization.label10: 'Name & Family',
     AppKeyLocalization.label12: 'Edit Profile',
     AppKeyLocalization.label13: 'Peopli',
     AppKeyLocalization.label14: 'Add Photos',
     AppKeyLocalization.label15: 'Male',
     AppKeyLocalization.label16: 'Female',
     AppKeyLocalization.label17: 'Gender',
     AppKeyLocalization.label18: 'Save',
     AppKeyLocalization.label19: 'Cancel',
     AppKeyLocalization.label20: 'Post',
     AppKeyLocalization.label21: 'Comment',
     AppKeyLocalization.label22: 'Does not exist',
     AppKeyLocalization.label23: 'Login',
     AppKeyLocalization.label24: 'Password',
     AppKeyLocalization.label25: 'Signup',
     AppKeyLocalization.label26: 'Forgot your password?',
     AppKeyLocalization.label27: 'Pay attention',
     AppKeyLocalization.label28: 'Are you sure you want to exit the app?',
     AppKeyLocalization.label29: 'Confirm',
     AppKeyLocalization.label30: "Please Enter Code",
     AppKeyLocalization.label31: 'Verify-Login',
     AppKeyLocalization.label32: 'Enter old password',
     AppKeyLocalization.label33: 'Enter new password',
     AppKeyLocalization.label34: 'Send',
     AppKeyLocalization.label35: "Don't have an Account?",
     AppKeyLocalization.label36:  "Please select the desired degree",
     AppKeyLocalization.label37: 'Location',
     AppKeyLocalization.label38: "search country",
     AppKeyLocalization.label39: 'Jobs',
     AppKeyLocalization.label40: 'Submit',
     AppKeyLocalization.label41: "Add photo or video:",
     AppKeyLocalization.label42: "text...",
     AppKeyLocalization.label43: 'EN',
     AppKeyLocalization.label44: 'FA',
     AppKeyLocalization.label45: "Add Photos",
     AppKeyLocalization.label46: 'Add Memory',
     AppKeyLocalization.label47: 'Date',
     AppKeyLocalization.label48: 'Subject',
     AppKeyLocalization.label49: 'UserName',
     AppKeyLocalization.label50: 'Known as',
     AppKeyLocalization.label51: 'Name',
     AppKeyLocalization.label52: 'Family',
     AppKeyLocalization.label53: 'Confirm Password',
     AppKeyLocalization.label54: 'Create',
     AppKeyLocalization.label55: 'Email',
     AppKeyLocalization.label56: 'Location permission denied',
     AppKeyLocalization.label57: 'User Location',
     AppKeyLocalization.label58: 'Get Current Location',
     AppKeyLocalization.label59: 'Are you sure you want to exit the app?',
     AppKeyLocalization.label60: 'vote',
     AppKeyLocalization.label61: 'Works',
     AppKeyLocalization.label62: 'Lives',
     AppKeyLocalization.label63: 'Has born in',
     AppKeyLocalization.label64: 'Edit',
     AppKeyLocalization.label65: '',
     AppKeyLocalization.label66: '',
     AppKeyLocalization.label67: '',
     AppKeyLocalization.label68: '',
     AppKeyLocalization.label69: '',
     AppKeyLocalization.label70: '',
     AppKeyLocalization.label71: '',
     AppKeyLocalization.label72: '',
     AppKeyLocalization.label73: '',
     AppKeyLocalization.label74: '',
     AppKeyLocalization.label75: '',
     AppKeyLocalization.label76: '',
     AppKeyLocalization.label77: '',
     AppKeyLocalization.label78: '',
     AppKeyLocalization.label79: '',
     AppKeyLocalization.label80: '',
     AppKeyLocalization.label81: '',
     AppKeyLocalization.label82: '',
     AppKeyLocalization.label83: '',
     AppKeyLocalization.label84: '',
     AppKeyLocalization.label85: '',
     AppKeyLocalization.label86: '',
     AppKeyLocalization.label87: '',
     AppKeyLocalization.label88: '',
     AppKeyLocalization.label89: '',
     AppKeyLocalization.label90: '',
     AppKeyLocalization.label91: '',
     AppKeyLocalization.label92: '',
     AppKeyLocalization.label93: '',
     AppKeyLocalization.label94: '',
     AppKeyLocalization.label95: '',
     AppKeyLocalization.label96: '',
     AppKeyLocalization.label97: '',
     AppKeyLocalization.label98: '',
     AppKeyLocalization.label99: '',
     AppKeyLocalization.label100: '',
};
}